version: '3'
services:
  web:
    build:
      context: .
    volumes:
      - .:/polycode
    ports:
      - "5000:4000"
    links:
      - mongodb
    depends_on:
      - mongodb
    command: mix local.hex --force
    command: mix local.rebar --force
  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_USER=mongodb
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
      command: mongod --smallfiles --logpath=/dev/null # --quiet
